const SRC = {
  sa:["StockAnalysis.com: quote and analyst forecast pages","https://stockanalysis.com/"],
  qntipo:["StockAnalysis.com: Quantinuum (QNT) profile and IPO data","https://stockanalysis.com/stocks/QNT/"],
  qntbuzz:["IPO Scoop: Quantinuum priced upsized IPO at $60 (June 2026)","https://www.iposcoop.com/the-ipo-buzz-quantinuum-priced-upsized-ipo-at-60-5-above-range/"],
  qntgo:["Gotrade: Quantinuum's Nasdaq debut and Honeywell's stake (June 2026)","https://www.heygotrade.com/en/news/quantinuum-nasdaq-debut-quantum-computing-stocks/"],
  helios:["Quantinuum: commercial launch of Helios (Nov 2025)","https://www.quantinuum.com/press-releases/quantinuum-announces-commercial-launch-of-new-helios-quantum-computer-that-offers-unprecedented-accuracy-to-enable-generative-quantum-ai-genqai"],
  qntyahoo:["Yahoo Finance: Quantinuum's IPO puts the quantum rally to the test","https://finance.yahoo.com/markets/article/honeywells-quantinuums-ipo-puts-the-quantum-stock-rally-to-the-test-154531114.html"],
  qnt600:["The Quantum Insider: Quantinuum's $600M raise at a $10B valuation (Sept 2025)","https://thequantuminsider.com/2025/09/04/honeywell-announces-600-million-capital-raise-for-quantinuum-at-10-billion-pre-money-equity-valuation-to-advance-quantum-computing-at-scale/"],
  qntchips:["The Quantum Insider: Quantinuum finalizes $100M award with GlobalFoundries and Monarch (Sept 2026)","https://thequantuminsider.com/2026/09/08/quantinuum-finalizes-100m-us-government-award-quantum-manufacturing/"],
  qntbmw:["Quantum Computing Report: Quantinuum and BMW multi-year partnership (May 2026)","https://quantumcomputingreport.com/quantinuum-and-bmw-group-expand-collaboration-with-multi-year-partnership/"],
  infq:["Quantum Computing Report: Infleqtion goes public on NYSE (Feb 2026)","https://quantumcomputingreport.com/infleqtion-goes-public-on-nyse-via-spac-merger-raising-550-million/"],
  hq:["The Quantum Insider: Horizon Quantum goes public via SPAC (Mar 2026)","https://thequantuminsider.com/2026/03/19/horizon-quantum-goes-public-via-spac-raises-120-million/"],
  xndu:["Bennett Jones: Crane Harbor completes combination with Xanadu (Mar 2026)","https://www.bennettjones.com/News/Client-Work/Crane-Harbor-Completes-Business-Combination-with-Xanadu-Quantum-Technologies"],
  xnduval:["BetaKit: Xanadu's $3.6B SPAC deal (Nov 2025)","https://betakit.com/xanadu-to-go-public-on-nasdaq-and-tsx-in-3-6-billion-usd-spac-deal/"],
  xndutower:["Xanadu and Tower Semiconductor deepen collaboration (Feb 2026)","https://www.globenewswire.com/news-release/2026/02/19/3240857/0/en/Xanadu-and-Tower-Semiconductor-Deepen-Strategic-Collaboration-to-Accelerate-Photonic-Quantum-Hardware-Innovation.html"],
  iqm:["Dealroom: IQM lists on Nasdaq at $1.9B (July 2026)","https://dealroom.co/news/136905-iqm-lists-on-nasdaq-at-1-9b-becoming-europes-first-public-quantum-player/"],
  iqmout:["The Quantum Insider: IQM confirms 2026 outlook, €102M+ in orders (Aug 2026)","https://thequantuminsider.com/2026/08/04/iqm-confirms-2026-outlook-after-public-listing-citing-more-than-e102-million-in-orders"],
  pasqal:["The Star: Pasqal surges in Nasdaq debut (Aug 28, 2026)","https://www.thestar.com.my/tech/tech-news/2026/08/28/frances-quantum-computer-maker-pasqal-surges-in-nasdaq-debut"],
  pasqaltk:["Parameter: Pasqal (PSQL) rises 40% on its first day","https://parameter.io/pasqal-psql-stock-rockets-40-higher-in-first-day-of-nasdaq-trading/"],
  aramco:["The Quantum Insider: Aramco and Pasqal deploy Saudi Arabia's first quantum computer (Nov 2025)","https://thequantuminsider.com/2025/11/24/saudi-arabia-first-quantum-computer-aramco-pasqal/"],
  terra:["Quantum Computing Report: Terra Quantum and Axiom sign $3.5B SPAC agreement","https://quantumcomputingreport.com/terra-quantum-and-axiom-intelligence-corp-1-sign-definitive-business-combination-agreement-at-3-5-billion-valuation/"],
  eigenq:["Quantum Computing Report: EigenQ and Silicon Valley Acquisition Corp file S-4 (Aug 2026)","https://quantumcomputingreport.com/eigenq-and-silicon-valley-acquisition-corp-advance-3b-spac-merger-via-form-s-4-submission/amp/"],
  seeqc:["The Quantum Insider: SEEQC to go public via Allegro Merger Corp (Jan 2026)","https://thequantuminsider.com/2026/01/16/seeqc-to-go-public-through-merger-with-allegro-merger-corp/"],
  seeqcs1:["Quantum Computing Report: SEEQC files S-1 for a Nasdaq IPO","https://quantumcomputingreport.com/seeqc-files-form-s-1-for-nasdaq-ipo-parallel-to-ongoing-allegro-merger-process/"],
  ynet:["Ynet/Calcalist: Quantum Art and Classiq in SPAC talks (July 2026)","https://www.ynetnews.com/business/article/hypoglzegg"],
  qart:["The Quantum Insider: Quantum Art extends Series A to $140M (Apr 2026)","https://thequantuminsider.com/2026/04/27/quantum-art-extends-series-a-funding-to-140-million-with-participation-from-global-financial-leaders/"],
  quantisimo:["Goldesel: SEALSQ plans Quantisimo via GigCapital8 (June 2026)","https://goldesel.de/aktien/news/sealsq-plant-nasdaq-quantenplattform-quantisimo-loi-mit-gigcapital8-startet-deal-uber-575-mio-usd"],
  psiq:["TechSpot: PsiQuantum raises $1B at a $7B valuation (Sept 2025)","https://www.techspot.com/news/109433-psiquantum-raises-1-billion-hits-7-billion-valuation.html"],
  psiqlate:["Startup Daily: PsiQuantum's Brisbane build is running late (Dec 2025)","https://www.startupdaily.net/topic/global-tech/psiquantums-brisbane-build-is-already-running-very-late/"],
  psiqgf:["SDxCentral: Nvidia backs PsiQuantum; GlobalFoundries makes its chips","https://www.sdxcentral.com/news/nvidia-backs-photonic-quantum-chip-maker-valued-at-7b/"],
  iqmp:["Quantum Computing Report: Illinois breaks ground on its quantum park","https://quantumcomputingreport.com/illinois-breaks-ground-on-quantum-and-microelectronics-park-with-psiquantum-as-anchor-tenant/"],
  atom:["Atom Computing: $100M Series C (June 2026)","https://atom-computing.com/?p=1532"],
  magne:["Quantum Computing Report: Denmark's QuNorth to acquire Magne","https://quantumcomputingreport.com/denmarks-qunorth-to-acquire-50-logical-qubit-magne-quantum-computer-from-atom-computing-and-microsoft/"],
  quera:["The Quantum Insider: QuEra completes $230M financing (Feb 2025)","https://thequantuminsider.com/2025/02/11/quera-computing-completes-230-million-financing-to-accelerate-development-of-large-scale-fault-tolerant-quantum-computers/"],
  queranv:["The Quantum Insider: QuEra adds Nvidia's NVentures (Sept 2025)","https://thequantuminsider.com/2025/09/09/quera-secures-investment-from-nventures-expands-230-million-financing-round/"],
  oqc:["Quantum Computing Report: OQC closes £260M Series C (June 2026)","https://quantumcomputingreport.com/oxford-quantum-circuits-closes-260-million-series-c-round-to-scale-superconducting-quantum-infrastructure-globally/"],
  photonic:["HPCwire: Photonic Inc. closes $200M at a $2B valuation (May 2026)","https://www.hpcwire.com/off-the-wire/photonic-inc-announces-final-close-of-200m-funding-round-at-2b-valuation/"],
  alicebob:["NAI 500: Alice & Bob completes Series B extension (May 2026)","https://nai500.com/blog/2026/05/quantum-computing-funding-heats-up-again-as-alice-bob-completes-series-b-extension/"],
  qm:["Caplight: Quantum Machines funding and valuation","https://www.caplight.com/company/quantum-machines"],
  origin:["AI2 Work: Chinese quantum firms race to IPO (Aug 2026)","https://ai2.work/blog/five-chinese-quantum-firms-race-to-claim-the-first-quantum-ipo-crown"],
  ionqq2:["IonQ: second-quarter 2026 results","https://ionq.com/news/ionq-announces-record-second-quarter-2026-revenues-growing-287-yoy"],
  ionqqcr:["Quantum Computing Report: IonQ Q2 2026, guidance raised","https://quantumcomputingreport.com/ionq-reports-record-q2-2026-financial-results-revenue-soars-287-to-80-1m-full-year-guidance-raised-to-290m/"],
  ionqsky:["The Quantum Insider: IonQ completes SkyWater acquisition (July 2026)","https://thequantuminsider.com/2026/07/31/ionq-completes-skywater-acquisition-quantum-manufacturing/"],
  skycust:["Quantum Computing Report: IonQ to acquire SkyWater; foundry customers","https://quantumcomputingreport.com/ionq-to-acquire-skywater-technology-in-1-8-billion-vertical-integration-transaction/"],
  ionqnv:["IonQ: first QPU for Nvidia's Accelerated Quantum Research Center (Sept 2026)","https://investors.ionq.com/news/news-details/2026/IonQ-to-Advance-Quantum-Supercomputing-by-Bringing-First-QPU-to-NVIDIA-Accelerated-Quantum-Research-Center/default.aspx"],
  ionqrm:["IonQ: technology roadmap","https://ionq.com/roadmap"],
  ionqaz:["The Quantum Insider: IonQ, AstraZeneca, AWS and Nvidia (June 2025)","https://thequantuminsider.com/2025/06/09/ionq-speeds-quantum-accelerated-drug-development-application-in-partnership-with-astrazeneca-aws-and-nvidia/"],
  ionqnkt:["IonQ: partnership with NKT Photonics","https://ionq.com/news/ionq-announces-partnership-with-nkt-photonics-for-next-generation-laser"],
  rgti:["Quantum Computing Report: Rigetti Q2 2026 results","https://quantumcomputingreport.com/rigetti-computing-reports-q2-2026-financial-results-revenue-up-185-yoy-100m-chips-act-loi-and-hpe-supercomputing-partnership/"],
  rgtisec:["Rigetti: Q4 2025 results and contracts (SEC exhibit)","https://www.sec.gov/Archives/edgar/data/1838359/000110465926023446/rgti-20260304xex99d1.htm"],
  rgtiquanta:["The Quantum Insider: Rigetti finalizes $35M Quanta investment (Apr 2025)","https://thequantuminsider.com/2025/04/30/rigetti-finalizes-35-million-investment-as-quanta-partnership-moves-forward/"],
  qbts:["Quantum Computing Report: D-Wave Q2 2026 results","https://quantumcomputingreport.com/d-wave-reports-its-q2-2026-financial-results-showing-bookings-surge-technical-progress-and-qci-acquisition-impact/"],
  qbtsqci:["D-Wave: agreement to acquire Quantum Circuits (Jan 2026)","https://www.dwavequantum.com/company/newsroom/press-release/d-wave-to-acquire-quantum-circuits"],
  qbtssup:["HPCwire: D-Wave's supremacy claim draws an immediate challenge (Mar 2025)","https://www.hpcwire.com/2025/03/13/d-wave-reports-quantum-supremacy-stirs-immediate-challenge-and-rebuttal/"],
  qubt:["Quantum Computing Report: Quantum Computing Inc. Q2 2026 results","https://quantumcomputingreport.com/quantum-computing-inc-reports-q2-2026-financial-results-revenue-surges-to-5-6m-and-fab-2-launch-via-nhanced-acquisition/"],
  ibm:["IBM: new processors and the path to fault tolerance (Nov 2025)","https://newsroom.ibm.com/2025-11-12-ibm-delivers-new-quantum-processors,-software,-and-algorithm-breakthroughs-on-path-to-advantage-and-fault-tolerance"],
  ibmrm:["IBM: quantum roadmap (2026)","https://ibm.com/roadmaps/quantum/2026"],
  ibmamd:["HPCwire: IBM runs error correction on AMD FPGAs (Oct 2025)","https://www.hpcwire.com/2025/10/28/ibm-touts-affordable-quantum-error-correction-on-amd-fpgas/"],
  ibmriken:["The Quantum Insider: IBM and RIKEN unveil Quantum System Two (June 2025)","https://thequantuminsider.com/2025/06/24/ibm-riken-system-two/"],
  hsbc:["HSBC: quantum-enabled algorithmic trading with IBM (Sept 2025)","https://www.hsbc.com/news-and-views/news/media-releases/2025/hsbc-demonstrates-worlds-first-known-quantum-enabled-algorithmic-trading-with-ibm"],
  jpm:["JPMorgan Chase: certified randomness with Quantinuum (Mar 2025)","https://www.jpmorganchase.com/about/technology/news/certified-randomness"],
  echoes:["Quantum Computing Report: Google's verifiable advantage with Quantum Echoes (Oct 2025)","https://quantumcomputingreport.com/google-quantum-ai-achieves-verifiable-quantum-advantage-on-willow-chip-with-quantum-echoes-algorithm/"],
  googrm:["Quantum Zeitgeist: Google's quantum roadmap and neutral-atom effort","https://quantumzeitgeist.com/google-quantum-computing/"],
  atlantic:["The Quantum Insider: Atlantic Quantum joins Google Quantum AI (Oct 2025)","https://thequantuminsider.com/2025/10/03/atlantic-quantum-joins-google-quantum-ai/"],
  zurich:["Zurich Instruments: control systems for Atlantic Quantum","https://www.zhinst.com/en/news/zurich-instruments-provides-quantum-computing-control-systems-atlantic-quantum/"],
  maj2:["PostQuantum: analysis of Microsoft's Majorana 2 (June 2026)","https://postquantum.com/industry-news/microsoft-majorana-2-analysis/"],
  ocelot:["The Next Platform: AWS Ocelot cat qubits (Feb 2025)","https://www.nextplatform.com/2025/02/27/aws-cat-qubits-make-quantum-error-correction-effective-affordable/"],
  braket:["AWS: Amazon Braket quantum computers","https://aws.amazon.com/braket/quantum-computers/"],
  azure:["Microsoft Learn: Azure Quantum providers (Apr 2026)","https://learn.microsoft.com/en-us/azure/quantum/qc-target-list"],
  nvqlink:["Nvidia: NVQLink for quantum builders and labs (Oct 2025)","https://investor.nvidia.com/news/press-release-details/2025/NVIDIA-Introduces-NVQLink--Connecting-Quantum-and-GPU-Computing-for-17-Quantum-Builders-and-Nine-Scientific-Labs/default.aspx"],
  nvaqc:["Nvidia: Accelerated Quantum Research Center (Mar 2025)","https://investor.nvidia.com/news/press-release-details/2025/NVIDIA-to-Build-Accelerated-Quantum-Computing-Research-Center/default.aspx"],
  huang:["NBC: Jensen Huang says he was wrong about the quantum timeline (Mar 2025)","https://nbclosangeles.com/news/business/money-report/nvidia-ceo-huang-says-he-was-wrong-about-timeline-for-quantum-surprised-his-comments-hurt-stocks/3659492"],
  he3:["The Quantum Insider: Bluefors buys lunar helium-3 from Interlune (Sept 2025)","https://thequantuminsider.com/2025/09/17/bluefors-enters-deal-to-secure-lunar-helium-3-supply-from-interlune/"],
  he3b:["GeekWire: Interlune's deals with Maybell and the DOE (May 2025)","https://www.geekwire.com/2025/interlune-moon-mining-vermeer-maybell-quantum-doe/"],
  kide:["Bluefors: KIDE cryogenic platform for IBM","https://bluefors.com/stories/kide-cryogenic-platform-from-design-to-delivery/"],
  delft:["Quantum Computing Report: Bluefors and Delft Circuits partner (Sept 2025)","https://quantumcomputingreport.com/bluefors-and-delft-circuits-join-forces-on-scalable-quantum-i-o-for-next-generation-quantum-computers/"],
  form:["FormFactor: partnership with Delft Circuits (Mar 2025)","https://www.formfactor.com/press-release/formfactor-partners-with-delft-circuits-to-revolutionize-quantum-computing-interfacing"],
  maybell:["Quantum Computing Report: Maybell deploys fridges at Roadrunner Quantum Lab (July 2026)","https://quantumcomputingreport.com/maybell-quantum-deploys-dilution-refrigerators-at-roadrunner-quantum-lab/"],
  qdo:["The Quantum Insider: Quantum Design acquires Oxford NanoScience (Jan 2026)","https://thequantuminsider.com/2026/01/05/quantum-design-acquires-oxford-nanoscience-joining-two-historic-cryogeniccompanies/"],
  oxoqc:["Oxford Instruments: technology for OQC's quantum-AI data centre (Nov 2025)","https://www.oxinst.com/news/news/oxford-instruments-contributes-technology-to-oqc-quantum-ai-data-centre/"],
  oxrgti:["Oxford Instruments: atomic-layer etch tool for Rigetti (May 2026)","https://www.oxinst.com/news/oxford-instruments-to-supply-atomic-layer-etch-equipment-to-rigetti-computing-to-expand-advanced-quantum-fabrication-capabilities/"],
  keysight:["The Quantum Insider: Keysight control system in Fujitsu/RIKEN's 256-qubit computer (May 2025)","https://thequantuminsider.com/2025/05/16/keysight-quantum-control-system-embedded-within-fujitsu-and-rikens-world-leading-256-qubit-quantum-computer/"],
  qmjul:["The Quantum Insider: Jülich deploys Nvidia DGX Quantum with Quantum Machines (Sept 2025)","https://thequantuminsider.com/2025/09/18/julich-supercomputing-centre-to-deploy-nvidia-dgx-quantum-system-with-arque-systems-and-quantum-machines/"],
  qblox:["Quantum Computing Report: Qblox launches US manufacturing","https://quantumcomputingreport.com/qblox-launches-u-s-manufacturing-for-quantum-control-systems/amp/"],
  quantware:["The Quantum Insider: QuantWare raises $178M (May 2026)","https://thequantuminsider.com/2026/05/05/quantware-raises-178-million-to-build-quantum-processors-at-an-industrial-scale/"],
  riverlane:["Riverlane: Deltaflow 2 delivered to Rigetti and Infleqtion","https://www.riverlane.com/news/deltaflow-2-delivered-to-rigetti-and-infleqtion"],
  rlinfq:["Quantum Computing Report: Infleqtion and Riverlane MoU (Sept 2026)","https://quantumcomputingreport.com/infleqtion-and-riverlane-execute-strategic-mou-to-integrate-neutral-atom-hardware-with-real-time-qec-decoders/amp/"],
  qctrl:["The Quantum Insider: Q-CTRL Fire Opal on IBM, Rigetti, OQC and Diraq","https://thequantuminsider.com/2024/09/11/q-ctrl-expands-fire-opal-integration-to-leading-quantum-platforms-ibm-rigetti-oqc-and-diraq/"],
  classiq:["Classiq: IonQ, AMD and Qualcomm Ventures join its round","https://www.classiq.io/insights/ionq-amd-and-qualcomm-ventures-join-classiq-strategic-up-round"],
  qbi:["DARPA: Quantum Benchmarking Initiative Stage B selections","https://www.darpa.mil/research/programs/quantum-benchmarking-initiative/stage-b-selection"],
  loi:["The Quantum Insider: Commerce letters of intent with nine companies for $2B (May 2026)","https://thequantuminsider.com/2026/05/21/u-s-department-of-commerce-announces-letters-of-intent-with-9-companies-for-2-billion/"],
  chipsfin:["AI2 Work: Commerce takes equity stakes in D-Wave, Rigetti and Quantinuum (Sept 2026)","https://ai2.work/blog/commerce-takes-equity-stakes-in-d-wave-rigetti-and-quantinuum"],
  dwave8k:["D-Wave 8-K: CHIPS Act equity agreement (Sept 8, 2026)","https://www.sec.gov/Archives/edgar/data/0001907982/000190798226000141/chipsactpressrelease.htm"],
  doe:["Quantum Computing Report: DOE renews five national quantum centers for $625M","https://quantumcomputingreport.com/doe-announces-625-million-renewal-for-five-national-quantum-information-science-research-centers/"],
  nqi:["Nextgov: Senate committee approves quantum reauthorization (Apr 2026)","https://www.nextgov.com/emerging-tech/2026/04/senate-committee-approves-quantum-reauthorization-bill-7-amendments/412840/"],
  uk:["NQCC: £670M ten-year funding for the UK National Quantum Computing Centre","https://www.nqcc.ac.uk/?p=25020"],
  japan:["The Quantum Insider: Japan backs quantum startups (July 2025)","https://thequantuminsider.com/2025/07/31/japan-backs-quantum-startups-in-50-billion-push-for-tech-leadership/"],
  china:["The Quantum Insider: China's $138B hard-tech fund includes quantum (Mar 2025)","https://thequantuminsider.com/2025/03/07/china-launches-138-billion-government-backed-venture-fund-includes-quantum-startups/"],
  mck:["PostQuantum: McKinsey Quantum Technology Monitor 2026","https://postquantum.com/industry-news/mckinsey-quantum-monitor-2026/"],
  qedc:["HPCwire: QED-C says quantum computing market to reach $3B by 2028 (Apr 2026)","https://www.hpcwire.com/off-the-wire/qed-c-report-global-quantum-computing-market-to-double-by-2028-reaching-3b-in-revenue/"],
  gidney:["Gidney (2025): RSA-2048 with fewer than a million noisy qubits (arXiv)","https://arxiv.org/html/2505.15917v1"],
  rsa:["PostQuantum: newer, lower estimates for breaking RSA-2048","https://postquantum.com/industry-news/quantum-breakthrough-rsa-2048/"],
  gri:["PostQuantum: Global Risk Institute quantum threat timeline survey","https://postquantum.com/security-pqc/quantum-threat-timeline-report-2025/"],
  hqc:["NIST: HQC selected as a fifth post-quantum algorithm (Mar 2025)","https://www.nist.gov/news-events/news/2025/03/nist-selects-hqc-fifth-algorithm-post-quantum-encryption"],
  pqcdead:["The Quantum Insider: post-quantum migration deadlines (May 2026)","https://thequantuminsider.com/2026/05/08/post-quantum-migration-timelines-government-industry-impact/"],
  laes:["SEALSQ: Q1 2026 metrics and business update","https://www.sealsq.com/investors/news-releases/sealsq-reports-q1-2026-key-financial-and-operational-metrics-and-provides-business-update"],
  arqq:["Finviz: Arqit first-half fiscal 2026 results","https://finviz.com/news/356288/arqit-quantum-inc-announces-financial-results-for-first-half-of-fiscal-year-2026"],
  btq:["Quantum Computing Report: BTQ Technologies approved to list on Nasdaq","https://quantumcomputingreport.com/btq-technologies-receives-approval-to-list-on-nasdaq/"],
  sandbox:["Quantum Computing Report: SandboxAQ raises $95M at over $5.6B","https://quantumcomputingreport.com/sandboxaq-has-raised-an-additional-95-million-at-a-company-valuation-of-over-5-6-billion/"],
  selloff:["24/7 Wall St: IonQ, Rigetti and D-Wave down 30% in a month (July 29, 2026)","https://247wallst.com/investing/2026/07/29/ionq-rigetti-and-d-wave-quantum-are-down-30-in-a-month-is-more-pain-coming-for-quantum-computing-stocks/"],
  insider:["Crypto Briefing: quantum insiders sold about $895M of stock (Sept 2026)","https://cryptobriefing.com/quantum-computing-stocks-insider-selling-895-million/"],
  spac26:["Let's Data Science: how the 2026 quantum listings traded (Mar 2026)","https://letsdatascience.com/news/quantum-firms-pursue-public-listings-amid-breakthroughs-247f5aac"],
  sept8:["24/7 Wall St: quantum stocks rally on Commerce stakes (Sept 8, 2026)","https://247wallst.com/investing/2026/09/08/quantum-stocks-rally-as-commerce-department-takes-equity-stakes-rigetti-surges-6-d-wave-climbs-5/"]
};

const LANES = [
 {id:"parts", cls:"power", name:"Parts & tools: the picks and shovels",
  note:"These companies sell to many qubit makers at once, so they can do well no matter which type of qubit wins.",
  bands:[
   {id:"P1",label:"Cooling & helium-3",plain:"Superconducting and spin qubits work only near absolute zero (−273°C), inside dilution refrigerators that need scarce helium-3."},
   {id:"P2",label:"Chips, fabs & lasers",plain:"Factories that make qubit chips, ion traps and photonic chips, plus the lasers that control single atoms and ions."},
   {id:"P3",label:"Control, error fixing & software",plain:"Electronics that send pulses to the qubits, fast decoders that catch and fix errors as they happen, and the programming tools."},
   {id:"P8",label:"Post-quantum security",plain:"Not part of building quantum computers. These companies sell new encryption that a future quantum computer can't break.",coal:true}
 ]},
 {id:"build", cls:"hw", name:"Qubit builders, grouped by type of qubit",
  note:"Nobody knows yet which kind of qubit wins. Each type trades off speed, accuracy and how easily it scales.",
  bands:[
   {id:"H1",label:"Superconducting",plain:"Tiny circuits cooled near absolute zero. Fast and made with chip-industry tools, but error-prone and wiring-hungry."},
   {id:"H2",label:"Trapped ion",plain:"Single charged atoms held by electric fields and steered by lasers. The most accurate today, but slower."},
   {id:"H3",label:"Neutral atom",plain:"Uncharged atoms held in place by laser 'tweezers'. Easy to reach thousands of qubits; speed and accuracy still catching up."},
   {id:"H4",label:"Photonic",plain:"Qubits made of light, on chips from regular fabs. Easier to network, but lost photons are the big problem."},
   {id:"H5",label:"Spin in silicon",plain:"Single electrons in silicon, made like ordinary transistors. Potentially tiny and very scalable, but early."},
   {id:"H6",label:"Annealing",plain:"A special-purpose machine for optimization problems. Sells today, but can't run general quantum programs."}
 ]}
];

const N = {
 interlune:{b:"P1",n:"Interlune",t:"private · Seattle",role:"Plans to harvest helium-3 from the Moon, and source it on Earth, for quantum fridges.",
  f:["Bluefors agreed to buy up to 10,000 liters a year of lunar helium-3, for delivery 2028–2037 (Sept 2025).","Maybell Quantum is its first commercial customer: thousands of liters a year, 2029–2035.","Also has a DOE order for 3 liters by April 2029 and an Air Force contract for US-sourced helium-3.","Helium-3 sells for roughly $2,000–15,000 a liter, and Earth's supply is tiny."],s:["he3","he3b"]},
 bluefors:{b:"P1",n:"Bluefors",t:"private · Finland",role:"The leading maker of the dilution refrigerators that cool superconducting qubits.",
  f:["Built IBM's KIDE cryogenic platform, first delivered in 2023.","Signed the largest lunar helium-3 purchase so far, with Interlune.","Delft Circuits' cryogenic cabling comes pre-installed in its fridges (Sept 2025)."],s:["kide","he3","delft"]},
 maybell:{b:"P1",n:"Maybell Quantum",t:"private · Colorado",role:"Startup making smaller, simpler dilution refrigerators.",
  f:["Installed four fridges at New Mexico's Roadrunner Quantum Lab (July 2026), where QuEra is an anchor tenant.","Interlune's first commercial helium-3 customer."],s:["maybell","he3b"]},
 qdo:{b:"P1",n:"Quantum Design Oxford",t:"private · UK / US",role:"Oxford Instruments' former fridge business, now owned by Quantum Design.",
  f:["Quantum Design bought Oxford Instruments' NanoScience unit for £60M; the deal was done by January 2026.","Its Proteox LX fridge cools OQC's machine at OQC's New York data center (Nov 2025)."],s:["qdo","oxoqc"]},
 oxinst:{b:"P1",n:"Oxford Instruments",t:"LSE: OXIG · UK",role:"UK scientific-equipment maker. It sold its fridge unit but still sells chipmaking tools to qubit fabs.",
  f:["Sold its NanoScience (dilution refrigerator) unit to Quantum Design for £60M in 2025.","Supplying an atomic-layer etch tool to Rigetti's chip fab in Fremont (May 2026).","Quantum is now a small part of the business."],s:["qdo","oxrgti"]},
 formfactor:{b:"P1",n:"FormFactor",t:"FORM · California",role:"Chip-testing company that also sells cryogenic test systems and its own dilution fridges.",
  f:["Makes Flatiron dilution refrigerators and cryogenic probers for testing qubit chips.","Partners with Delft Circuits on cryogenic cabling (March 2025).","Most revenue comes from probe cards for ordinary chips, including AI memory."],s:["form"]},
 delft:{b:"P1",n:"Delft Circuits",t:"private · Netherlands",role:"Makes the flexible cryogenic cables that carry signals down to the qubits.",
  f:["Its Cri/oFlex cabling ships inside Bluefors fridges, up to 1,536 lines each.","Also supplies FormFactor's cryogenic test systems."],s:["delft","form"]},

 gfs:{b:"P2",n:"GlobalFoundries",t:"GFS · New York",role:"US chip foundry that makes PsiQuantum's photonic chips and Quantinuum's next ion traps.",
  f:["Makes PsiQuantum's photonic chipset at Fab 8 in New York.","Will build 300mm ion traps and electronics for Quantinuum under a $100M CHIPS award (Sept 2026).","Got a $375M CHIPS letter of intent in exchange for a government equity stake (May 2026)."],s:["psiqgf","qntchips","loi"]},
 skywater:{b:"P2",n:"SkyWater",t:"now part of IonQ · Minnesota",role:"US foundry that makes chips for several quantum companies; bought by IonQ.",
  f:["IonQ closed its roughly $1.8B purchase on July 31, 2026.","Foundry customers include D-Wave, PsiQuantum and Silicon Quantum Computing. How a rival's ownership affects them long term is a risk to watch."],s:["ionqsky","skycust"]},
 honeywell:{b:"P2",n:"Honeywell",t:"HON · North Carolina",role:"Industrial giant that controls Quantinuum and builds its ion traps.",
  f:["Kept about 48% of Quantinuum's votes after the June 2026 IPO.","Manufactured the ion trap inside Quantinuum's Helios computer.","Quantum is a small part of Honeywell's earnings, so the stock mostly moves on aerospace and automation."],s:["qntgo","helios"]},
 tower:{b:"P2",n:"Tower Semiconductor",t:"TSEM · Israel",role:"Specialty foundry making silicon-photonics parts for Xanadu.",
  f:["Expanded its high-volume photonics manufacturing deal with Xanadu (Feb 2026).","Most of its business is chips for phones, cars and data center optics."],s:["xndutower"]},
 monarch:{b:"P2",n:"Monarch Quantum",t:"private · US",role:"Supplies lasers and optical parts for Quantinuum's machines.",
  f:["Named as a supplier under Quantinuum's $100M CHIPS award (Sept 2026)."],s:["qntchips"]},
 nkt:{b:"P2",n:"NKT Photonics",t:"private · Denmark",role:"Laser maker supplying IonQ's next-generation systems.",
  f:["Partnership with IonQ on laser systems (Nov 2024)."],s:["ionqnkt"]},
 quantware:{b:"P2",n:"QuantWare",t:"private · Netherlands",role:"Sells ready-made superconducting qubit chips to labs and startups.",
  f:["Raised $178M led by Intel Capital (May 2026) to build a high-volume 'KiloFab'.","Has shipped chips to more than 50 customers in 20 countries."],s:["quantware"]},
 quanta:{b:"P2",n:"Quanta Computer",t:"2382.TW · Taiwan",role:"Taiwanese server maker (it also builds AI racks) and a strategic quantum investor.",
  f:["Bought about $35M of Rigetti stock and committed with Rigetti to over $100M of joint R&D over five years (2025).","Invested in Quantinuum's $600M round (Sept 2025)."],s:["rgtiquanta","qnt600"]},

 keysight:{b:"P3",n:"Keysight",t:"KEYS · California",role:"Test-equipment giant that also sells quantum control systems.",
  f:["Its control system runs inside Fujitsu and RIKEN's 256-qubit computer (May 2025).","Installed a large control system at Japan's AIST G-QuAT center (July 2025).","An Nvidia NVQLink partner."],s:["keysight","nvqlink"]},
 qm:{b:"P3",n:"Quantum Machines",t:"private · Israel",role:"The leading independent maker of qubit control systems.",
  f:["Its OPX1000 controller is paired with Nvidia's DGX Quantum at Germany's Jülich center (Sept 2025).","Ran Rigetti's Novera chip at 99.5% two-qubit accuracy (May 2026).","A founding partner of Nvidia's Boston quantum research center; a tenant at the Illinois quantum park."],s:["qmjul","nvaqc"]},
 qblox:{b:"P3",n:"Qblox",t:"private · Netherlands",role:"Control-electronics maker, now also building in the US.",
  f:["Started US manufacturing in Massachusetts, shipping from April 2026.","An Nvidia NVQLink partner."],s:["qblox","nvqlink"]},
 zurich:{b:"P3",n:"Zurich Instruments",t:"private · Switzerland",role:"Control systems for superconducting qubits.",
  f:["Supplied control systems to Atlantic Quantum, which Google bought in October 2025.","An Nvidia NVQLink partner."],s:["zurich","atlantic"]},
 amd:{b:"P3",n:"AMD",t:"AMD · California",role:"Its FPGA chips run real-time error correction, and it partners with IBM.",
  f:["IBM's error-correction decoder runs in real time on an AMD FPGA (Oct 2025).","Partnership with IBM on quantum-centric supercomputing (Aug 2025).","Invested in Classiq through AMD Ventures."],s:["ibmamd","classiq"]},
 nvidia:{b:"P3",n:"Nvidia",t:"NVDA · California",role:"Doesn't build qubits. It sells the GPUs, software and links that pair quantum computers with supercomputers.",
  f:["NVQLink (Oct 2025) connects quantum chips to Nvidia GPUs; about 19 qubit builders and 4 control-system makers signed on.","CUDA-Q is its quantum programming platform, used by PsiQuantum, Quantinuum and others.","Its venture arm has invested in PsiQuantum, Quantinuum, QuEra and Alice & Bob.","IonQ will install the first on-site quantum computer at Nvidia's Boston research center in 2027."],s:["nvqlink","nvaqc","ionqnv","psiq"]},
 riverlane:{b:"P3",n:"Riverlane",t:"private · UK",role:"Makes the fast decoders that find and fix qubit errors in real time.",
  f:["Delivered its Deltaflow 2 decoder to Rigetti and Infleqtion (2025) and integrated it with OQC's machine.","Signed an MoU with Infleqtion for its Sqale computer (Sept 2026)."],s:["riverlane","rlinfq"]},
 qctrl:{b:"P3",n:"Q-CTRL",t:"private · Australia",role:"Software that reduces errors on today's quantum computers.",
  f:["Its Fire Opal software runs on IBM, Rigetti, OQC and Diraq machines.","Uses Nvidia AI models to tune qubits automatically (April 2026)."],s:["qctrl"]},
 classiq:{b:"P3",n:"Classiq",t:"private · Israel",role:"Tools for writing quantum programs; reportedly in talks to go public.",
  f:["Investors include AMD, Qualcomm and IonQ (Nov 2025); over $200M raised.","Customers include BMW, Comcast, Rolls-Royce and SoftBank.","Reported in July 2026 to be in advanced talks for a SPAC listing at $2–5B."],s:["classiq","ynet"]},
 horizonq:{b:"P3",n:"Horizon Quantum",t:"HQ · Singapore",role:"Software for programming quantum computers, plus its own hardware testbed.",
  f:["Began trading on Nasdaq on March 20, 2026, after merging with dMY Squared (about $500M valuation, about $120M raised).","One of the smallest listed quantum companies; only two analysts cover it."],s:["hq"]},

 sealsq:{b:"P8",n:"SEALSQ",t:"LAES · Switzerland",role:"Makes security chips with post-quantum encryption built in.",
  f:["Q1 2026 revenue about $4.1M (+200%); expects its QS7001 post-quantum chip to start producing revenue in late 2026.","Its parent, WISeKey, plans a separate quantum company, Quantisimo, via a SPAC (non-binding letter, about $575M, aimed at Q1 2027)."],s:["laes","quantisimo"]},
 arqit:{b:"P8",n:"Arqit",t:"ARQQ · UK",role:"Sells quantum-safe encryption software.",
  f:["Revenue was only $623K in the six months to March 2026, with $35.9M of cash in May 2026.","Very small company; the stock is extremely volatile and has no analyst target."],s:["arqq"]},
 btq:{b:"P8",n:"BTQ Technologies",t:"BTQ · Canada",role:"Post-quantum security for blockchains and payments.",
  f:["Moved up to the Nasdaq in Sept 2025; also trades in Canada and Frankfurt."],s:["btq"]},
 sandboxaq:{b:"P8",n:"SandboxAQ",t:"private · California",role:"Alphabet spinout selling post-quantum security and AI simulation.",
  f:["Valued at over $5.6B after raising another $95M (July 2025)."],s:["sandbox"]},

 ibm:{b:"H1",n:"IBM",t:"IBM · New York",role:"The superconducting leader, with the clearest public roadmap to an error-corrected machine in 2029.",
  f:["Nighthawk (120 qubits) shipped at the end of 2025; targets are 7,500 operations by end of 2026 and 1,000+ qubits in 2028.","Starling (2029): 200 error-corrected 'logical' qubits running 100M operations. Blue Jay (2033+): 2,000 logical qubits.","Expects researchers to confirm quantum advantage by the end of 2026.","Largest CHIPS letter of intent: $1B for a government equity stake (May 2026). In DARPA's QBI Stage B."],s:["ibm","ibmrm","loi","qbi"]},
 google:{b:"H1",n:"Google Quantum AI",t:"via GOOGL · California",role:"Alphabet's quantum lab. It hit the key error-correction milestone and showed the first checkable quantum advantage.",
  f:["Willow (Dec 2024) showed errors falling as more qubits are added, the threshold every roadmap depends on.","'Quantum Echoes' (Oct 2025, Nature) ran 13,000x faster than top supercomputers on a result that can be checked.","Added neutral atoms as a second approach (March 2026) and bought Atlantic Quantum (Oct 2025).","Its goal is about a million physical qubits; quantum is a tiny part of Alphabet."],s:["echoes","googrm","atlantic"]},
 rigetti:{b:"H1",n:"Rigetti Computing",t:"RGTI · California",role:"Pure-play superconducting company with its own chip fab.",
  f:["Q2 2026 revenue $5.1M (+185%); $541M of cash and no debt.","Its 108-qubit Cepheus chip reaches about 99.1% two-qubit accuracy; aims for about 1,000-qubit systems within three years.","Orders include an ~$8.4M 108-qubit system for India's C-DAC.","The US government took an equity stake: up to $100M for about 7.7M shares at $12.92 (Sept 2026)."],s:["rgti","rgtisec","chipsfin"]},
 iqm:{b:"H1",n:"IQM",t:"IQMX · Finland",role:"Europe's leading superconducting builder; listed via SPAC in July 2026.",
  f:["Began trading on Nasdaq July 2, 2026, at about a $1.9B valuation, through Real Asset Acquisition Corp.","Sells whole machines to supercomputing centers; its first US system went to Oak Ridge National Lab (June 2026).","Order backlog above €102M (Aug 2026). Available on AWS Braket."],s:["iqm","iqmout"]},
 oqc:{b:"H1",n:"Oxford Quantum Circuits",t:"private · UK",role:"UK superconducting builder putting machines inside data centers.",
  f:["Raised £260M (about $350M) led by Bullhound Capital, with £100M from the British Business Bank (June 2026).","Runs a quantum computer at its New York data center."],s:["oqc","oxoqc"]},
 alicebob:{b:"H1",n:"Alice & Bob",t:"private · France",role:"Builds 'cat qubits' designed to need far less error correction.",
  f:["Nvidia's venture arm joined, bringing its Series B to €100M (May 2026).","Amazon's Ocelot chip uses the same cat-qubit idea."],s:["alicebob","ocelot"]},
 seeqc:{b:"H1",n:"SEEQC",t:"private · New York",role:"Superconducting chips with digital control built in; trying to go public.",
  f:["Agreed to merge with Allegro Merger Corp at about $1B (Jan 2026) and also filed for a Nasdaq IPO as SEQC. Not trading yet."],s:["seeqc","seeqcs1"]},

 ionq:{b:"H2",n:"IonQ",t:"IONQ · Maryland",role:"The biggest pure play by revenue, buying its way into networking, sensing, space and chipmaking.",
  f:["Q2 2026 revenue $80.1M (+287%); 2026 guidance raised to $280–290M, not counting SkyWater.","Bought Oxford Ionics ($1.075B), SkyWater (~$1.8B), most of ID Quantique, Capella, Lightsynq, Vector Atomic and Skyloom.","About $2B of cash after the SkyWater deal; Q2 GAAP net loss of $1.87B.","Its roadmap claims 800 logical qubits in 2027 and 80,000 by 2030, far more aggressive than its peers."],s:["ionqq2","ionqqcr","ionqsky","ionqrm"]},
 quantinuum:{b:"H2",n:"Quantinuum",t:"QNT · Colorado / UK",role:"The trapped-ion leader with the most accurate machines; went public in June 2026.",
  f:["IPO at $60 on June 4, 2026, raising about $1.68B; Honeywell kept about 48% of the votes.","Helios (Nov 2025): 98 qubits, 99.921% two-qubit accuracy, 48 error-corrected logical qubits.","Next: Sol in 2027 and Apollo, a fault-tolerant machine, in 2029.","RIKEN was about 60% of 2025 revenue. Trailing revenue is about $23M, so the stock trades near 500 times sales.","Government equity stake of up to $100M finalized in Sept 2026."],s:["qntipo","qntbuzz","helios","qntyahoo","qntgo","chipsfin"]},
 quantumart:{b:"H2",n:"Quantum Art",t:"private · Israel",role:"Trapped-ion startup reportedly in talks to go public.",
  f:["Extended its Series A to $140M (April 2026).","Reported in July 2026 to be in advanced talks for a SPAC listing at $2–5B."],s:["qart","ynet"]},

 quera:{b:"H3",n:"QuEra",t:"private · Boston",role:"Neutral-atom leader that grew out of Harvard and MIT research.",
  f:["Raised over $230M from Google, SoftBank and others (Feb 2025); Nvidia invested in Sept 2025.","Installing a machine at Japan's AIST beside Nvidia GPUs; its Aquila machine is on AWS Braket.","In DARPA's QBI Stage B."],s:["quera","queranv","qbi"]},
 atom:{b:"H3",n:"Atom Computing",t:"private · California",role:"Neutral-atom builder making the hardware for Microsoft's machines.",
  f:["Building 'Magne' with Microsoft for Denmark: 50 logical qubits from 1,225 atoms, due late 2026 or early 2027.","Raised $100M led by Third Point (June 2026); $100M CHIPS letter of intent.","In DARPA's QBI Stage B."],s:["atom","magne","qbi"]},
 infleqtion:{b:"H3",n:"Infleqtion",t:"INFQ · Colorado",role:"Neutral-atom computers plus quantum clocks and sensors; listed via SPAC in February 2026.",
  f:["Began trading on the NYSE on Feb 17, 2026, through Churchill Capital X ($1.8B valuation, $550M+ raised).","Sells atomic clocks and sensors today, which bring in revenue while the computer matures.","$100M CHIPS letter of intent; works with Riverlane on error correction."],s:["infq","loi","rlinfq"]},
 pasqal:{b:"H3",n:"Pasqal",t:"PSQL · France",role:"French neutral-atom builder; listed via SPAC in August 2026.",
  f:["Debuted on Nasdaq Aug 28, 2026, through Bleichroeder Acquisition II, at about a $2B valuation; it closed about 40% higher on day one with about $360M of cash.","Installed a 200-qubit machine for Aramco in Saudi Arabia (Nov 2025); available on Azure Quantum.","Its roadmap targets about 100 logical qubits by 2029."],s:["pasqal","pasqaltk","aramco"]},

 psiquantum:{b:"H4",n:"PsiQuantum",t:"private · California",role:"The best-funded private quantum company, betting on light-based qubits made in ordinary chip fabs.",
  f:["Raised $1B at a $7B valuation (Sept 2025) from BlackRock, Temasek, Baillie Gifford and Nvidia's venture arm.","Building sites in Brisbane (A$940M Australian government package) and Chicago (anchor of Illinois' $500M quantum park).","Brisbane is reported up to a year late, now looking closer to 2030.","Chips made by GlobalFoundries; $100M CHIPS letter of intent; in the final phase of DARPA's US2QC program."],s:["psiq","psiqlate","iqmp","psiqgf","qbi"]},
 xanadu:{b:"H4",n:"Xanadu",t:"XNDU · Toronto",role:"Canadian photonic builder; listed via SPAC in March 2026.",
  f:["Began trading on Nasdaq and the TSX on March 27, 2026, through Crane Harbor ($3.6B valuation, about $302M raised).","Down roughly 55% over the past year; analyst targets ($16–43) haven't caught up with the price.","Chips made with Tower Semiconductor; in DARPA's QBI Stage B."],s:["xndu","xnduval","xndutower","qbi"]},
 photonic:{b:"H4",n:"Photonic Inc.",t:"private · Canada",role:"Links spin qubits in silicon together with light.",
  f:["Raised over $200M at a $2B valuation (May 2026).","In DARPA's QBI Stage B."],s:["photonic","qbi"]},
 qci:{b:"H4",n:"Quantum Computing Inc.",t:"QUBT · New Jersey",role:"Makes photonic chips and optical machines; today it looks more like a small chip foundry than a quantum leader.",
  f:["Q2 2026 revenue $5.6M, with about $1.3B of cash and investments from large share sales.","Spent about $180M in 2026 buying Luminar Semiconductor, NuCrypt and NHanced Semiconductors."],s:["qubt"]},

 intel:{b:"H5",n:"Intel",t:"INTC · Oregon",role:"Makes silicon spin-qubit chips in its own fabs and invests in QuantWare.",
  f:["Spin qubits look like ordinary transistors, so Intel can use its normal factories; it released its 12-qubit Tunnel Falls chip to researchers in 2023.","Intel Capital led QuantWare's $178M round (May 2026).","Quantum is a tiny part of Intel; the stock moves on its foundry and PC business."],s:["quantware"]},
 diraq:{b:"H5",n:"Diraq",t:"private · Australia",role:"Silicon spin qubits designed for standard chip fabs.",
  f:["Up to $38M CHIPS letter of intent (May 2026); in DARPA's QBI Stage B; a tenant at the Illinois quantum park."],s:["loi","qbi","iqmp"]},
 sqc:{b:"H5",n:"Silicon Quantum Computing",t:"private · Australia",role:"Builds qubits from single atoms placed in silicon.",
  f:["In DARPA's QBI Stage B; a SkyWater foundry customer."],s:["qbi","skycust"]},

 dwave:{b:"H6",n:"D-Wave Quantum",t:"QBTS · California",role:"Sells annealing machines for optimization today, and is adding general-purpose gate-model computers.",
  f:["Q2 2026 revenue $3.1M, but first-half bookings were $35.5M, including a $20M system for Florida Atlantic University.","Bought Quantum Circuits for $550M (Jan 2026) to get superconducting gate-model qubits; its first system is due in 2026.","$546M of cash; government equity stake of up to $100M finalized Sept 2026.","Claimed 'quantum supremacy on a useful problem' (Science, March 2025); some researchers disputed it."],s:["qbts","qbtsqci","dwave8k","qbtssup"]},

 amazon:{b:"R",n:"Amazon (AWS Braket)",t:"AMZN · Seattle",role:"Rents out other companies' quantum computers and is building its own Ocelot chip.",
  f:["Braket offers machines from AQT, IonQ, IQM, QuEra and Rigetti (Rigetti's 108-qubit chip was added April 2026).","Ocelot (Feb 2025) uses cat qubits and claims up to 90% less error-correction overhead.","Quantum is tiny for Amazon; AI and AWS drive the stock."],s:["braket","ocelot"]},
 microsoft:{b:"R",n:"Microsoft (Azure Quantum)",t:"MSFT · Redmond",role:"Rents out IonQ, Pasqal, Quantinuum and Rigetti machines, and is developing its own Majorana qubits.",
  f:["Majorana 2 (June 2026) claims 1,000x more stable qubits and moved its target for a scalable machine from 2033 to 2029. Critics say the evidence is still thin.","Building 'Magne' with Atom Computing for Denmark; a long-time Quantinuum partner.","In the final phase of DARPA's US2QC program, alongside PsiQuantum."],s:["azure","maj2","magne","qbi"]},

 usgov:{b:"U",n:"US government",t:"Commerce · DARPA · DOE",role:"The biggest single funder, and now also a shareholder.",
  f:["Commerce signed CHIPS letters of intent for about $2.0B across nine companies in exchange for equity stakes (May 2026). D-Wave, Rigetti and Quantinuum were finalized at up to $100M each (Sept 8).","DARPA's Quantum Benchmarking Initiative is testing whether a useful machine is possible by 2033; 11 companies are in Stage B.","DOE renewed five national quantum research centers with $625M (Nov 2025)."],s:["loi","chipsfin","qbi","doe"]},
 jpmorgan:{b:"U",n:"JPMorgan Chase",t:"JPM · bank",role:"Wall Street's most active quantum user.",
  f:["Generated certified random numbers on Quantinuum's H2 machine (Nature, March 2025).","An investor in Quantinuum."],s:["jpm","qnt600"]},
 hsbc:{b:"U",n:"HSBC",t:"HSBC · bank",role:"Tested quantum bond trading on IBM hardware.",
  f:["Reported up to 34% better predictions of whether bond trades would fill (Sept 2025)."],s:["hsbc"]},
 bmw:{b:"U",n:"BMW",t:"carmaker",role:"Uses quantum computers for materials and engineering research.",
  f:["Multi-year deal with Quantinuum covering Helios, Sol and Apollo (May 2026).","Also a Classiq customer."],s:["qntbmw","classiq"]},
 astrazeneca:{b:"U",n:"AstraZeneca",t:"drugmaker",role:"Testing quantum chemistry for drug discovery.",
  f:["With IonQ, AWS and Nvidia, ran a chemistry workflow that IonQ says was over 20x faster (June 2025)."],s:["ionqaz"]},
 aramco:{b:"U",n:"Aramco",t:"oil · Saudi Arabia",role:"Bought Saudi Arabia's first quantum computer.",
  f:["Installed Pasqal's 200-qubit machine in Dhahran (Nov 2025); its venture arm invests in Pasqal."],s:["aramco"]},
 riken:{b:"U",n:"RIKEN (Japan)",t:"national lab",role:"Japan's national research institute and a big buyer of machines.",
  f:["Hosts IBM's first Quantum System Two outside the US, linked to the Fugaku supercomputer (June 2025).","Was about 60% of Quantinuum's 2025 revenue.","Fujitsu and RIKEN's 256-qubit machine uses Keysight control electronics."],s:["ibmriken","qntgo","keysight"]},
 labs:{b:"U",n:"Labs & universities",t:"Oak Ridge · Jülich · C-DAC · FAU",role:"Research centers that buy whole machines to sit beside their supercomputers.",
  f:["Oak Ridge National Lab: the first US IQM system (June 2026).","Florida Atlantic University: a $20M D-Wave Advantage2.","India's C-DAC: an ~$8.4M Rigetti 108-qubit system.","Germany's Jülich: a D-Wave system, plus Quantum Machines control with Nvidia."],s:["iqmout","qbts","rgtisec","qmjul"]},
 qunorth:{b:"U",n:"QuNorth (Denmark)",t:"EIFO · Novo Nordisk Foundation",role:"Danish program buying the Magne machine from Atom Computing and Microsoft.",
  f:["€80M from Denmark's EIFO and the Novo Nordisk Foundation for Magne: 50 logical qubits, due late 2026 or early 2027."],s:["magne"]}
};

const S = {
 ionq:{tk:"IONQ",risk:4,mv:"−39% in the month to July 29",
  bull:"The most revenue of any pure play, and growing fast; plenty of cash; owns its own fab (SkyWater) and a networking business; first quantum computer at Nvidia's research center.",
  bear:"Most of the growth comes from acquisitions, losses are large, and the roadmap promises far more than anyone has shown. Insiders have been big sellers.",
  cat:"Q3 results in early November; SkyWater's first full quarter; progress toward its 256-qubit system."},
 quantinuum:{tk:"QNT",risk:4,mv:"about 27% below its $60 IPO price",
  bull:"The most accurate machines in the industry, a clear path to fault tolerance in 2029, Honeywell and JPMorgan behind it, and $1.68B of IPO cash.",
  bear:"About $23M of trailing revenue against an $11–12B market value (around 500 times sales), and RIKEN alone was about 60% of 2025 revenue.",
  cat:"Its first earnings reports as a public company; Sol in 2027; the end of the IPO lock-up (usually about six months after listing), when insiders can start selling."},
 rigetti:{tk:"RGTI",risk:4,mv:"−30% in the month to July 29",
  bull:"Owns its fab, has $541M of cash and no debt, the US government is now a shareholder, and Quanta is a partner.",
  bear:"Revenue is tiny ($5M a quarter) and its accuracy trails IBM and Google, so it has to win on cost or speed.",
  cat:"Delivering the C-DAC system and progress toward its goal of about 1,000 qubits."},
 dwave:{tk:"QBTS",risk:4,mv:"−30% in the month to July 29",
  bull:"The only company selling quantum machines for practical optimization today, with $35.5M of first-half bookings and a gate-model computer from Quantum Circuits on the way.",
  bear:"Quarterly revenue is still about $3M; annealing can't run general quantum programs, and its supremacy claim was disputed.",
  cat:"Converting bookings to revenue; the first Quantum Circuits gate-model system in 2026."},
 qci:{tk:"QUBT",risk:4,mv:"−24% in the month to July 29",
  bull:"About $1.3B of cash and a growing photonic chip foundry business after its 2026 acquisitions.",
  bear:"Small, early revenue, and its market value has relied on share sales; it is the furthest from a useful quantum computer among the big four pure plays.",
  cat:"Revenue from the NHanced and Luminar fabs."},
 infleqtion:{tk:"INFQ",risk:4,
  bull:"Already sells clocks and sensors, has $100M of government backing on the way, and listed with over $550M of cash.",
  bear:"Few analysts cover it, and SPAC listings often keep falling after the first year.",
  cat:"First quarters of public results; finalizing its CHIPS award."},
 xanadu:{tk:"XNDU",risk:4,
  bull:"Photonic chips can be made in existing fabs and networked easily; it is in DARPA's Stage B.",
  bear:"Down about 55% over the past year. Only 3–4 analysts cover it, so the average target is easily skewed.",
  cat:"DARPA QBI progress and new manufacturing milestones with Tower."},
 horizonq:{tk:"HQ",risk:4,
  bull:"Software sells across every hardware type.",
  bear:"Tiny company with only two analysts covering it.",
  cat:"Customer wins for its programming tools."},
 iqm:{tk:"IQMX",risk:4,
  bull:"Europe's leader in selling whole machines to supercomputing centers, with over €100M in orders.",
  bear:"Only one analyst target so far, and SPAC shares tend to drift after listing.",
  cat:"Its first full quarters as a public company; more US system sales."},
 pasqal:{tk:"PSQL",risk:4,
  bull:"A neutral-atom leader with a 200-qubit machine installed at Aramco and about $360M of cash.",
  bear:"Just listed, so there's little analyst coverage and the stock can swing hard.",
  cat:"Its 250-qubit advantage demonstration targeted for 2026."},
 ibm:{tk:"IBM",risk:1,
  bull:"The clearest dated roadmap to an error-corrected computer (2029), the biggest CHIPS letter of intent ($1B), and a profitable software and consulting business underneath.",
  bear:"Quantum is a small part of IBM, so even big breakthroughs move the stock only a little.",
  cat:"Kookaburra and any confirmed quantum-advantage results by the end of 2026."},
 google:{tk:"GOOGL",risk:1,
  bull:"The strongest quantum science team, with both of the big 2024–2025 milestones.",
  bear:"Quantum is a rounding error inside Alphabet; you're really buying search, cloud and AI.",
  cat:"Its next roadmap milestone, a long-lived logical qubit."},
 microsoft:{tk:"MSFT",risk:1,
  bull:"Sells access to many machines through Azure and has its own Majorana bet, which would be a big edge if it works.",
  bear:"Majorana results are disputed, and quantum barely affects Microsoft's earnings.",
  cat:"Delivery of Magne in Denmark; peer review of Majorana 2."},
 amazon:{tk:"AMZN",risk:1,
  bull:"Braket rents out most of the leading machines, and Ocelot is a credible in-house design.",
  bear:"Quantum is negligible next to AWS and retail.",
  cat:"A next-generation Ocelot chip."},
 nvidia:{tk:"NVDA",risk:2,
  bull:"Wins whichever qubit type wins, because every quantum computer needs GPUs for control, error fixing and simulation. Also owns stakes in PsiQuantum, Quantinuum and QuEra.",
  bear:"Quantum is tiny for Nvidia; the stock trades on AI data center spending.",
  cat:"NVQLink adoption; the IonQ system arriving in 2027."},
 amd:{tk:"AMD",risk:2,
  bull:"Its FPGAs already run IBM's real-time error correction, and it partners with IBM on quantum supercomputing.",
  bear:"Quantum is a tiny slice; AMD moves on AI GPUs and CPUs.",
  cat:"Whether IBM keeps using AMD chips as error correction scales up."},
 intel:{tk:"INTC",risk:3,
  bull:"Spin qubits could be made in Intel's normal fabs at huge scale.",
  bear:"Intel's quantum program is small and quiet, and the stock depends on its foundry turnaround.",
  cat:"Any new spin-qubit chip or quantum foundry customer."},
 honeywell:{tk:"HON",risk:1,
  bull:"Holds about 48% of Quantinuum's votes, so it owns a big piece of the trapped-ion leader with a profitable industrial business underneath.",
  bear:"Quantinuum's falling share price lowers the value of that stake.",
  cat:"Quantinuum's share price and lock-up expiry."},
 gfs:{tk:"GFS",risk:2,
  bull:"Makes chips for PsiQuantum and Quantinuum, has a $375M CHIPS letter of intent, and is the main US-owned foundry.",
  bear:"Quantum is small; most revenue comes from chips for phones, cars and industry.",
  cat:"Finalizing its CHIPS award; PsiQuantum's production ramp."},
 keysight:{tk:"KEYS",risk:1,
  bull:"A profitable test-equipment leader that sells quantum control systems to labs and Japan's biggest projects.",
  bear:"Quantum is a small part of revenue.",
  cat:"New quantum control-system orders."},
 formfactor:{tk:"FORM",risk:2,
  bull:"Sells fridges and cryogenic test systems to qubit makers, and its main business benefits from AI memory testing.",
  bear:"Quantum is a small part of revenue; it is cyclical with chip spending.",
  cat:"Probe-card demand from HBM memory makers."},
 oxinst:{tk:"OXIG.L",risk:2,cur:"GBp",
  bull:"Still sells tools to qubit fabs, such as Rigetti's.",
  bear:"Sold its quantum fridge business in 2025, so its quantum exposure is now small.",
  cat:"Orders from quantum and semiconductor customers.",note:"Priced in British pence (GBp)."},
 quanta:{tk:"2382.TW",risk:2,cur:"TWD",
  bull:"A profitable AI server builder with stakes in Rigetti and Quantinuum.",
  bear:"Quantum is a rounding error; it moves on AI server orders.",
  cat:"AI rack shipments.",note:"Priced in Taiwan dollars."},
 tower:{tk:"TSEM",risk:2,
  bull:"A specialty foundry for photonics, which both photonic quantum and AI optics need.",
  bear:"Quantum is a tiny customer group.",
  cat:"Silicon-photonics orders for AI data centers."},
 sealsq:{tk:"LAES",risk:4,
  bull:"Government deadlines to switch to post-quantum encryption (2027–2035) create demand for chips like its QS7001.",
  bear:"Tiny revenue and only a couple of analysts; it has a history of issuing shares.",
  cat:"QS7001 production revenue in late 2026; the Quantisimo SPAC."},
 arqit:{tk:"ARQQ",risk:4,
  bull:"Sells encryption that governments must eventually adopt.",
  bear:"Revenue is tiny and there's no analyst target.",cat:"New government contracts."},
 btq:{tk:"BTQ",risk:4,bull:"Post-quantum security for crypto and payments.",bear:"Very small and early.",cat:"Commercial customers."},
 skywater:{via:"Now part of IonQ.",alias:"ionq"},
 psiquantum:{via:"Private. Indirect exposure: Nvidia (NVDA) invested through its venture arm, and GlobalFoundries (GFS) makes its chips."},
 quera:{via:"Private. Indirect exposure through Alphabet (GOOGL) and Nvidia (NVDA), both investors."},
 atom:{via:"Private. Its main partner is Microsoft (MSFT)."},
 alicebob:{via:"Private. Nvidia (NVDA) is an investor."},
 quantware:{via:"Private. Intel (INTC) led its latest round."},
 classiq:{via:"Private, reportedly in SPAC talks. AMD and IonQ are investors."},
 quantumart:{via:"Private, reportedly in SPAC talks."},
 seeqc:{via:"Private. Merger with Allegro Merger Corp and an IPO filing (SEQC) are pending."},
 oqc:{via:"Private."}, bluefors:{via:"Private."}, qm:{via:"Private."}, riverlane:{via:"Private."}, qctrl:{via:"Private."},
 qdo:{via:"Private (owned by Quantum Design)."}, photonic:{via:"Private."}, diraq:{via:"Private."}, sandboxaq:{via:"Private."}
};

const E = [
 ["interlune","bluefors","d","lunar helium-3, up to 10,000 L a year from 2028"],
 ["interlune","maybell","d","helium-3 for 2029–2035; first customer"],
 ["delft","bluefors","d","cryogenic cabling built into its fridges"],
 ["delft","formfactor","d","cabling for cryogenic test systems"],
 ["bluefors","ibm","d","KIDE cryogenic platform"],
 ["oxinst","qdo","p","sold its fridge unit for £60M (2025)"],
 ["qdo","oqc","d","Proteox LX fridge for its New York site"],
 ["oxinst","rigetti","d","atomic-layer etch tool for its fab (2026)"],
 ["gfs","psiquantum","d","makes its photonic chips"],
 ["gfs","quantinuum","d","300mm ion traps under a $100M CHIPS award"],
 ["honeywell","quantinuum","d","builds the Helios ion trap; ~48% of votes"],
 ["monarch","quantinuum","d","lasers and optics"],
 ["nkt","ionq","d","laser systems"],
 ["tower","xanadu","d","high-volume photonics manufacturing"],
 ["ionq","skywater","p","bought it; closed July 2026"],
 ["skywater","dwave","d","foundry"],
 ["skywater","psiquantum","d","foundry"],
 ["skywater","sqc","d","foundry"],
 ["intel","quantware","p","Intel Capital led its $178M round"],
 ["quanta","rigetti","p","~$35M stake plus $100M+ joint R&D"],
 ["quanta","quantinuum","p","investor (Sept 2025)"],
 ["keysight","riken","d","control system for the 256-qubit machine"],
 ["qm","labs","d","OPX1000 controller with Nvidia at Jülich"],
 ["zurich","google","d","control systems for Atlantic Quantum, now Google's"],
 ["amd","ibm","d","FPGAs run its real-time error decoder"],
 ["amd","classiq","p","investor"],
 ["ionq","classiq","p","investor"],
 ["riverlane","rigetti","d","Deltaflow 2 error decoder"],
 ["riverlane","infleqtion","d","decoder; MoU Sept 2026"],
 ["riverlane","oqc","d","Deltaflow 2 error decoder"],
 ["qctrl","ibm","d","Fire Opal error-reduction software"],
 ["qctrl","rigetti","d","Fire Opal error-reduction software"],
 ["classiq","bmw","d","quantum programming software"],
 ["nvidia","quantinuum","d","GPUs linked to Helios via NVQLink; investor"],
 ["nvidia","psiquantum","p","CUDA-Q software; investor"],
 ["nvidia","quera","p","investor (Sept 2025)"],
 ["nvidia","alicebob","p","investor (May 2026)"],
 ["ionq","nvidia","d","first on-site QPU at Nvidia's quantum center (2027)"],
 ["google","quera","p","investor in its $230M round"],
 ["ionq","amazon","d","on AWS Braket"],
 ["rigetti","amazon","d","on AWS Braket"],
 ["iqm","amazon","d","on AWS Braket"],
 ["quera","amazon","d","on AWS Braket"],
 ["ionq","microsoft","d","on Azure Quantum"],
 ["quantinuum","microsoft","d","on Azure; joint logical-qubit work"],
 ["pasqal","microsoft","d","on Azure Quantum"],
 ["rigetti","microsoft","d","on Azure Quantum"],
 ["atom","qunorth","d","Magne hardware"],
 ["microsoft","qunorth","d","Magne software and error correction"],
 ["quantinuum","jpmorgan","d","certified randomness; JPM is an investor"],
 ["quantinuum","bmw","d","multi-year access to Helios, Sol and Apollo"],
 ["quantinuum","riken","d","about 60% of its 2025 revenue"],
 ["ibm","hsbc","d","bond-trading trial"],
 ["ibm","riken","d","Quantum System Two beside Fugaku"],
 ["ionq","astrazeneca","d","chemistry workflow with AWS and Nvidia"],
 ["pasqal","aramco","d","200-qubit machine in Dhahran"],
 ["iqm","labs","d","first US system, at Oak Ridge"],
 ["dwave","labs","d","$20M Advantage2 for Florida Atlantic Univ."],
 ["rigetti","labs","d","108-qubit system for India's C-DAC"],
 ["usgov","ibm","p","$1B CHIPS equity letter of intent"],
 ["usgov","gfs","p","$375M CHIPS equity letter of intent"],
 ["usgov","dwave","p","up to $100M for equity, finalized"],
 ["usgov","rigetti","p","up to $100M for equity, finalized"],
 ["usgov","quantinuum","p","up to $100M for equity, finalized"],
 ["usgov","psiquantum","p","$100M letter of intent"],
 ["usgov","infleqtion","p","$100M letter of intent"],
 ["usgov","atom","p","$100M letter of intent"],
 ["usgov","diraq","p","up to $38M letter of intent"]
];

const BUYERS = ["usgov","jpmorgan","hsbc","bmw","astrazeneca","aramco","riken","labs","qunorth"];
const RBAND = ["amazon","microsoft"];
const GROUP = {P1:"Parts & tools",P2:"Parts & tools",P3:"Control & software",P8:"Post-quantum security",H1:"Qubit makers",H2:"Qubit makers",H3:"Qubit makers",H4:"Qubit makers",H5:"Qubit makers",H6:"Qubit makers",R:"Big tech",U:"Customers"};
N.ibm.g="Big tech"; N.google.g="Big tech"; N.intel.g="Big tech"; N.nvidia.g="Big tech"; N.amd.g="Big tech"; N.honeywell.g="Big tech";
const RISK = ["","Lower","Medium","High","Very high"];

const THEMES = [
 {t:"Big companies with a quantum lab",ids:["ibm","google","honeywell","microsoft","amazon"],risk:1,
  why:"Quantum is a small slice of these businesses, so they won't double on a breakthrough, but they also won't go to zero if useful quantum computers take until the 2030s. IBM has the clearest roadmap, Google the strongest science, and Honeywell holds about 48% of Quantinuum's votes.",
  watch:"IBM's quantum-advantage claims by the end of 2026, Microsoft's Majorana evidence, and Quantinuum's share price feeding into Honeywell."},
 {t:"The pure plays",ids:["ionq","quantinuum","rigetti","dwave","qci"],risk:4,
  why:"These rise and fall on quantum news alone. After the July selloff, analysts' average targets sit 50–150% above prices, but revenue is tiny next to their market values: Quantinuum trades near 500 times sales. IonQ has by far the most revenue, Quantinuum the most accurate machines, and Rigetti, D-Wave and Quantinuum now have the US government as a shareholder.",
  watch:"Q3 results in early November, new share sales that dilute holders, and insider selling."},
 {t:"The 2026 SPAC class",ids:["infleqtion","xanadu","iqm","pasqal","horizonq"],risk:4,
  why:"Five quantum companies listed through SPACs this year. SPACs let companies go public earlier than a normal IPO, and many keep falling after they list. Xanadu is down about 55% over the past year. Few analysts cover these, so a single target can swing the average.",
  watch:"Lock-up expiries when early holders can sell, cash burn, and whether 2026 orders turn into revenue."},
 {t:"Picks and shovels",ids:["nvidia","keysight","gfs","formfactor","amd","tower"],risk:2,
  why:"They sell to every type of qubit, so they don't need to pick the winner, and their main businesses are profitable. Quantum is small for each one, so treat it as a free option on top of the core business rather than the reason to buy.",
  watch:"NVQLink adoption, GlobalFoundries' government-backed quantum manufacturing, and new control-system orders."},
 {t:"Post-quantum security",ids:["sealsq","arqit","btq"],risk:4,
  why:"Whether or not quantum computers turn useful for business soon, governments have set deadlines from 2027 to 2035 to replace today's encryption, so that spending happens anyway. But these listed names are tiny, and much of the money may go to big security and chip companies instead.",
  watch:"SEALSQ's QS7001 chip revenue in late 2026 and the NSA's 2027 deadline for new systems."},
 {t:"Owning the private leaders indirectly",ids:["nvidia","google","honeywell","quanta","intel"],risk:2,
  why:"You can't buy PsiQuantum, QuEra, Atom Computing or Alice & Bob directly. Nvidia has invested in PsiQuantum, QuEra, Alice & Bob and Quantinuum; Alphabet in QuEra; Quanta in Rigetti and Quantinuum; Intel in QuantWare. Each stake is small compared with the company that owns it.",
  watch:"New private rounds at higher prices, which would lift these stakes on paper."}
];

const UI = {
  topic:"Quantum computing · supply chain & stocks",
  rband:["Big tech clouds","Most customers rent quantum computers over the internet instead of buying one. Amazon and Microsoft resell other companies' machines and are also building their own."],
  buyers:["Customers &amp; funders","Who pays for quantum computing today: governments, national labs, banks, drugmakers and carmakers."],
  bandR:"Cloud access", bandU:"Customer or funder",
  laneTxt:{u:"Customer or funder",dc:"Cloud",power:"Parts & tools",coal:"Post-quantum security",hw:"Qubit builder"},
  intro:["The pill on each company is the gap between its latest price and the average analyst target. Quantum targets are unusually far from prices, so read them with extra caution.","Companies without a pill are private or have no analyst target; the panel says how to get exposure, if any.","Dashed lines are investments, ownership or government letters of intent; solid lines are supply, sales or service deals."],
  filters:["All","Qubit makers","Parts & tools","Control & software","Big tech","Post-quantum security"],
  start:"quantinuum",
  noticeTail:"Quantum targets are especially unreliable: few analysts cover these stocks, and many targets haven't caught up with this year's price drops."
};

/* Listing history for the 2026 class (reference = IPO price, or the $10 a SPAC share starts at) */
const LISTINGS = [
 {id:"quantinuum",how:"IPO",when:"June 4, 2026",ref:60,val:"about $14–16B",with:"traditional IPO, $1.68B raised"},
 {id:"infleqtion",how:"SPAC",when:"Feb 17, 2026",ref:10,val:"$1.8B",with:"Churchill Capital Corp X"},
 {id:"horizonq",how:"SPAC",when:"Mar 20, 2026",ref:10,val:"about $500M",with:"dMY Squared"},
 {id:"xanadu",how:"SPAC",when:"Mar 27, 2026",ref:10,val:"$3.6B",with:"Crane Harbor Acquisition"},
 {id:"iqm",how:"SPAC",when:"July 2, 2026",ref:10,val:"about $1.9B",with:"Real Asset Acquisition"},
 {id:"pasqal",how:"SPAC",when:"Aug 28, 2026",ref:10,val:"about $2B",with:"Bleichroeder Acquisition II"}
];
