"""Build quantum.html from the shared page engine in index.html plus src/quantum/*.

Run after editing src/quantum/* or the engine in index.html:
    python scripts/build_quantum.py
It also bakes in a snapshot of today's prices from data/stocks.json, so the page
still shows numbers if the live data can't load.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src" / "quantum"

index = (ROOT / "index.html").read_text()
css = index[index.index("<style>") + len("<style>"):index.index("</style>")]
eng_start = index.index("const APP = Object.assign(")
eng_end = index.index("</script>", eng_start)
engine = index[eng_start:eng_end]

data = (SRC / "data.js").read_text()
body = (SRC / "body.html").read_text()
extra_css = (SRC / "extra.css").read_text()
extra_js = (SRC / "extra.js").read_text()

stocks = json.loads((ROOT / "data" / "stocks.json").read_text())
snap = {}
for k, q in stocks["stocks"].items():
    if q and q.get("px"):
        snap[k] = {"px": q["px"], "avg": q.get("avg"), "lo": q.get("lo"), "hi": q.get("hi"), "n": q.get("n"),
                   "r": q.get("rating"), "fpe": q.get("fpe"), "cur": q.get("currency"), "chg1d": q.get("chg1d")}
snap_js = f"""
/* price snapshot baked in at build time ({stocks.get('asof_label', stocks.get('asof'))}); replaced by live data when it loads */
const SNAP = {json.dumps(snap, separators=(',', ':'))};
const SNAP_D = {json.dumps(stocks.get('asof_short') or stocks.get('asof'))};
for (const [id, q] of Object.entries(SNAP)) {{
  if (!S[id]) {{ if (id === "qtum") S.qtum = {{tk: "QTUM"}}; else continue; }}
  const s = S[id]; if (!s.tk) continue;
  for (const k of ["px","avg","lo","hi","n","r","fpe","cur","chg1d"]) if (q[k] != null && s[k] == null) s[k] = q[k];
  if (s.avg && (s.lo == null || s.hi == null)) {{ s.lo = s.lo ?? s.avg; s.hi = s.hi ?? s.avg; }}
  if (!s.d) s.d = SNAP_D;
}}
"""

init = """
build();
makeRows(); buildFilters(); renderTable(); buildThemes(); pageRefresh();
document.querySelectorAll(".static [data-go]").forEach(b=>b.addEventListener("click",()=>select(b.dataset.go,true)));
let start=UI.start;
try{ const h=location.hash.slice(1); if(N[h]) start=h; }catch(e){}
select(start);
if(APP.app){ loadLive().then(initWatchlist); }
const ro=new ResizeObserver(()=>draw()); ro.observe(map);
if(document.fonts && document.fonts.ready) document.fonts.ready.then(draw);
const mq=matchMedia("(prefers-color-scheme: dark)"); mq.addEventListener && mq.addEventListener("change",draw);
new MutationObserver(draw).observe(document.documentElement,{attributes:true,attributeFilter:["data-theme"]});
"""
# the engine in index.html ends with its own init block; cut it off and use ours
cut = engine.index("\nbuild();\nmakeRows();")
engine = engine[:cut]

html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="description" content="Interactive map of the quantum computing supply chain: who supplies whom, who's leading, public stocks with analyst targets, and which private companies may go public.">
<title>Fridge to Qubit</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Archivo:wdth,wght@75..100,500..800&family=IBM+Plex+Mono:wght@400;500&family=Public+Sans:wght@400;500;600&display=swap">
<style>{css}
{extra_css}</style>
</head>
<body>
{body}
<script src="config.js"></script>
<script>
/* GENERATED by scripts/build_quantum.py from src/quantum/ and the engine in index.html. Edit those, then rebuild. */
{data}
{snap_js}
{engine}
{extra_js}
{init}
</script>
</body>
</html>
"""
(ROOT / "quantum.html").write_text(html)
print("wrote quantum.html", len(html), "bytes")
